In [4]:
using LinearAlgebra
q1 = [-37 -16 -66 96 11]
q2 = [-100 230 100 -34 24]
q3 = [-15 20 -10 52 20]
q4 = [1 0 0 0 0]
q5 = [0 1 0 0 0]

1×5 Matrix{Int64}:
 0  1  0  0  0

In [5]:
q1 = q1/ norm(q1)

1×5 Matrix{Float64}:
 -0.298951  -0.129276  -0.533265  0.775658  0.0888775

In [7]:
q2 = q2 - (q1*q2')q1
q2 = q2/ norm(q2)

1×5 Matrix{Float64}:
 -0.470012  0.839691  0.224139  0.0993886  0.117864

In [10]:
q3 = q3 - (q1*q3')q1 - (q2*q3')q2
q3 = q3/ norm(q3)

1×5 Matrix{Float64}:
 0.575355  0.0821969  0.418799  0.463631  0.521406

In [13]:
q4 = q4 - (q1*q4')q1 - (q2*q4')q2 - (q3*q4')q3 
q4 = q4/ norm(q4)

1×5 Matrix{Float64}:
 0.598902  0.515485  -0.492619  0.0197789  -0.364043

In [14]:
q5 = q5 - (q1*q5')q1 - (q2*q5')q2 - (q3*q5')q3 - (q4*q5')q4
q5 = q5/ norm(q5)

1×5 Matrix{Float64}:
 -1.46716e-15  0.0756714  -0.497317  -0.416091  0.757507

In [26]:
println(q1*q2')
println(q1*q3')
println(q1*q4')
println(q1*q5')
println(q2*q3')
println(q2*q4')
println(q2*q5')
println(q3*q4')
println(q3*q5')
println(q4*q5')

[5.932724773857937e-18;;]
[5.843474943447922e-17;;]
[-2.4035054479968163e-17;;]
[1.156851759032321e-17;;]
[3.351930395605562e-17;;]
[1.760229856919899e-20;;]
[2.570656149341609e-15;;]
[-2.4510914801150135e-17;;]
[-7.578599728646851e-16;;]
[3.57795379089255e-16;;]


In [20]:
A = zeros(2,5)
A[1,:] = q4
A[2,:] = q5

1×5 Matrix{Float64}:
 -1.46716e-15  0.0756714  -0.497317  -0.416091  0.757507

In [22]:
b = [2 15 2 -13 2]

1×5 Matrix{Int64}:
 2  15  2  -13  2

In [23]:
a = A*b'

2×1 Matrix{Float64}:
 6.959631187105747
 7.064638955085694